# Generated by Django 3.2.16 on 2025-01-18 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20250118_0006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
    ]
