# Generated by Django 3.2.16 on 2025-01-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250112_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_subscribed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Подписка'),
        ),
    ]
