# Generated by Django 3.2.16 on 2025-01-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_subscribed',
        ),
    ]
