# Generated by Django 3.2.16 on 2025-01-19 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_myuser_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя может содержать толькобуквы, цифры, и символы: . @ + - _', regex='^[\\w.@+-]+$')]),
        ),
    ]
